import type { Metadata } from "next";
import { Ubuntu_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/themeProvide";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/sidebar";
import { SiteHeader } from "@/components/layout/site-header";
import { DateRangeProvider } from "@/context/dateRangeContext";
import { ApolloWrapper } from "@/providers/apolloProvide";
import StoreProvider from "@/providers/reduxStoreProvider";
import NoInternetConnection from "@/components/error/NoInternet";

const ubuntuSans = Ubuntu_Sans({
  variable: "--font-ubuntu-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ubuntuSans.variable} ${geistMono.variable} antialiased`}
      >
        <NoInternetConnection>
          <StoreProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ApolloWrapper>
                <DateRangeProvider>
                  <SidebarProvider
                    style={
                      {
                        "--sidebar-width": "calc(var(--spacing) * 72)",
                        "--header-height": "calc(var(--spacing) * 12)",
                      } as React.CSSProperties
                    }
                  >
                    <AppSidebar variant="inset" />
                    <SidebarInset>
                      <SiteHeader />
                      {children}
                    </SidebarInset>
                  </SidebarProvider>
                </DateRangeProvider>
              </ApolloWrapper>
            </ThemeProvider>
          </StoreProvider>
        </NoInternetConnection>
      </body>
    </html>
  );
}
